In [1]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = '해보지 않으면 해낼 수 없다'

result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


# 2026.10.8(목) 19h~

In [1]:
import sys
!{sys.executable} -m pip uninstall -y opencv-python
!{sys.executable} -m pip install --force-reinstall --no-deps opencv-python-headless==4.9.0.80
!{sys.executable} -m pip install "numpy<2"

Found existing installation: opencv-python 5.0.0.93
Uninstalling opencv-python-5.0.0.93:
  Successfully uninstalled opencv-python-5.0.0.93
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-macosx_10_16_x86_64.whl.metadata (20 kB)
Using cached opencv_python_headless-4.9.0.80-cp37-abi3-macosx_10_16_x86_64.whl (55.7 MB)
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.9.0.80
    Uninstalling opencv-python-headless-4.9.0.80:
      Successfully uninstalled opencv-python-headless-4.9.0.80
  Using cached numpy-1.26.4-cp311-cp311-macosx_10_9_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-macosx_10_9_x86_64.whl (20.6 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the followi

In [1]:
import sys; print(sys.executable)   # /opt/anaconda3/envs/voice-ai/bin/python 이어야 함
import numpy, tensorflow, cv2
print(numpy.__version__, tensorflow.__version__, cv2.__version__)

/opt/anaconda3/envs/voice-ai/bin/python


2026-10-08 19:31:30.606308: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


1.26.4 2.16.2 4.9.0


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

samples = ['The cat sat on the mat.', 'The dog ate my homework.']

tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples) # sequences의 형태?
print(f"sequences = {sequences}")      # 내용 보기 = [[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
print(len(sequences))                  # 문장 개수 = 2
print([len(s) for s in sequences])     # 문장별 단어 개수 = [6, 5]

one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
print(f"one_hot_results = {one_hot_results}")

word_index = tokenizer.word_index # 단어 사전
print(f"word_index = {word_index}")

print('Found %s unique tokens.' % len(word_index))

x = to_categorical(sequences[0], num_classes=10) # 왜 num_classes 10?
print(x)
y = to_categorical(sequences[1], num_classes=10)
print(y)                                   

sequences = [[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
2
[6, 5]
one_hot_results = [[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
word_index = {'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}
Found 9 unique tokens.
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


one_hot_results 읽는 법

[[0. 1. 1. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]]

- 행 = 문장, 열 = 단어 번호예요. 모양이 (2, 1000)이라 문장 2개에 칸이 1000개(num_words=1000)예요. ...는 가운데 칸을 생략해서 보여주는 거예요.
- 값이 1이면 그 단어가 문장에 있다는 뜻이고, 0이면 없다는 뜻이에요(mode='binary').
- 칸 번호는 tokenizer.word_index의 번호와 같아요. 예상되는 번호는 the:1, cat:2, sat:3, on:4, mat:5, dog:6, ate:7, my:8, homework:9예요.
- 0번 칸은 항상 0이에요(번호가 1부터 시작해서 비어 있는 칸).

그래서 첫 문장(The cat sat on the mat.)은 1~5번 칸이 1이고, 둘째 문장(The dog ate my homework.)은 1, 6, 7, 8, 9번 칸이 1이에요. 둘 다 the(1번)가 있어서 첫 칸이 1이고, 둘째 칸이 1이냐 0이냐는 cat이 있느냐(2번)로
갈려요. 출력과 맞아요.

직접 해독해 보기
import numpy as np
print(one_hot_results.shape)                         # (2, 1000)

for i, row in enumerate(one_hot_results):
    idx = np.where(row == 1)[0]                      # 1인 칸의 번호들
    print(idx, [tokenizer.index_word[j] for j in idx])
예상 결과(실행은 안 해 봤어요):
[1 2 3 4 5] ['the', 'cat', 'sat', 'on', 'mat']
[1 6 7 8 9] ['the', 'dog', 'ate', 'my', 'homework']

주의할 점
- 첫 문장에서 the가 두 번 나오지만 binary는 있는지만 표시해서 1이에요. 몇 번 나왔는지는 mode='count'로 하면 2가 돼요.
- 단어 순서 정보는 사라져요. "개가 고양이를 물었다"와 "고양이가 개를 물었다"가 같은 벡터가 될 수 있어요. 이 한계 때문에 이후에 순서를 다루는 RNN과 임베딩을 배우는 걸로 알고 있어요

In [6]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
#단어 빈도수 세기
#전처리 하려는 세개의 문장을 정합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.'
       ]
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(docs)       # 토큰화 함수에 문장 적용
#단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다. 
print("\n단어 카운트:\n", token.word_counts) 
#Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.
 
#출력되는 순서는 랜덤입니다. 
print("\n문장 카운트: ", token.document_count)
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '나누어': 1, '텍스트의': 2, '단어를': 1, '먼저': 1, '합니다': 1, '토큰화': 3, '딥러닝에서': 2, '인식됩니다': 1, '해야': 1, '단어로': 1, '사용': 1, '있습니다': 1, '결과는': 1, '할': 1, '한': 1, '수': 1})

각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

# 토큰화 
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index) # 단어 사전

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


# 2026.10.8(목) 20h~

In [29]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
import warnings

warnings.filterwarnings('ignore')

# 10개 dummy data(가짜, 작은 사이즈의) 리스트, 클래스(긍정 or 부정 등?)가 없는 문장, 굳이 분류하자면 왕 1 vs 여왕 0으로 할 수 있겠지만, 10개로는 어차피 훈련 안 됨
sentences = [
    "왕은 나라를 다스리는 남자입니다.",
    "여왕은 나라를 다스리는 여자입니다.",
    "남자가 왕이 되었습니다.",
    "여자가 여왕이 되었습니다.",
    "왕과 여왕은 함께 궁전에서 살고 있습니다.",
    "남자와 여자가 파티에 참석했습니다.",
    "왕은 충성스러운 신하들을 거느립니다.",
    "여왕은 아름다운 드레스를 입고 있었습니다.",
    "남자가 여왕의 조언자가 되었습니다.",
    "여자가 왕의 자리를 노리고 있습니다."
]

tokenizer = Tokenizer(
    # 조사 붙은 단어까지 구분되도록 최소 필터만 적용
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'
)

In [30]:
tokenizer.fit_on_texts(sentences)

print("-- 참고 --")
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.document_count)
print(tokenizer.word_docs)
print("----------")

sequences = tokenizer.texts_to_sequences(sentences) # 각 문장의 토큰들이 숫자로 바뀜?

word_index = tokenizer.word_index
print("단어 목록/사전 = word_index = ", word_index)

padded = pad_sequences(sequences, padding='post')
print("패딩된 시퀀스 = \n", padded)

vocab_size = len(word_index) + 1
embedding_dim = 8 # 간단한 실습은 2, 4, 8개 정도면 됨 vs Naver 영화 리뷰 감정 분류 5천개 데이터 2세트는 32, 64개 vs 언어 모델? 128, 256개 vs 조금 더 큰 모델은 1024개 vs gpt 같은 건 수천/몇만 차원..
max_len = padded.shape[1]

-- 참고 --
{'여왕은': 1, '되었습니다': 2, '여자가': 3, '왕은': 4, '나라를': 5, '다스리는': 6, '남자가': 7, '있습니다': 8, '남자입니다': 9, '여자입니다': 10, '왕이': 11, '여왕이': 12, '왕과': 13, '함께': 14, '궁전에서': 15, '살고': 16, '남자와': 17, '파티에': 18, '참석했습니다': 19, '충성스러운': 20, '신하들을': 21, '거느립니다': 22, '아름다운': 23, '드레스를': 24, '입고': 25, '있었습니다': 26, '여왕의': 27, '조언자가': 28, '왕의': 29, '자리를': 30, '노리고': 31}
OrderedDict([('왕은', 2), ('나라를', 2), ('다스리는', 2), ('남자입니다', 1), ('여왕은', 3), ('여자입니다', 1), ('남자가', 2), ('왕이', 1), ('되었습니다', 3), ('여자가', 3), ('여왕이', 1), ('왕과', 1), ('함께', 1), ('궁전에서', 1), ('살고', 1), ('있습니다', 2), ('남자와', 1), ('파티에', 1), ('참석했습니다', 1), ('충성스러운', 1), ('신하들을', 1), ('거느립니다', 1), ('아름다운', 1), ('드레스를', 1), ('입고', 1), ('있었습니다', 1), ('여왕의', 1), ('조언자가', 1), ('왕의', 1), ('자리를', 1), ('노리고', 1)])
10
defaultdict(<class 'int'>, {'남자입니다': 1, '다스리는': 2, '나라를': 2, '왕은': 2, '여왕은': 3, '여자입니다': 1, '되었습니다': 3, '왕이': 1, '남자가': 2, '여자가': 3, '여왕이': 1, '있습니다': 2, '함께': 1, '왕과': 1, '궁전에서': 1, '살고': 1, '남자와': 1, '참석했습니다': 1, '파티에': 1, '신하들을': 1, '거느

In [31]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim)) # input_length=max_len, embedding 벡터 layer
model.add(Flatten()) # 분류기로 변환?
model.add(Dense(1, activation='sigmoid')) # 출력층 맞나? 여기는 왜 sigmoid 활성화 함수?

model.compile(optimizer='adam', loss='binary_crossentropy') # metrics=['accuracy'], 2진 분류, 이 예시에서는 의미가 없기 때문에 평가지표 accuracy 안 썼지만 감정 분류 등에는 유용할 수 있음
model.summary()

model.fit(padded, np.ones((len(sentences), 1)), epochs=10, verbose=2) # x = padded, y = dummy 1행렬
model.summary()

embedding_matrix = model.layers[0].get_weights()[0]

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
1/1 - 5s - 5s/step - loss: 0.6878
Epoch 2/10
1/1 - 1s - 533ms/step - loss: 0.6812
Epoch 3/10
1/1 - 0s - 319ms/step - loss: 0.6747
Epoch 4/10
1/1 - 0s - 212ms/step - loss: 0.6683
Epoch 5/10
1/1 - 0s - 323ms/step - loss: 0.6619
Epoch 6/10
1/1 - 0s - 356ms/step - loss: 0.6555
Epoch 7/10
1/1 - 0s - 264ms/step - loss: 0.6492
Epoch 8/10
1/1 - 0s - 153ms/step - loss: 0.6430
Epoch 9/10
1/1 - 0s - 242ms/step - loss: 0.6367
Epoch 10/10
1/1 - 0s - 175ms/step - loss: 0.6305


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 6, 8)           │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 48)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 917 (3.59 KB)

 Trainable params: 305 (1.19 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 612 (2.39 KB)

In [32]:
for word in word_index:
    if "왕" in word:
        print(f"\n* 단어 '{word}'의 embedding vector:")
        print(embedding_matrix[word_index[word]])


* 단어 '여왕은'의 embedding vector:
[-0.05639926  0.04374003  0.01471849  0.04282713 -0.01552615  0.05903339
 -0.00289831 -0.033106  ]

* 단어 '왕은'의 embedding vector:
[-0.03418493  0.01929132  0.02582967  0.0220907  -0.01921635 -0.0106393
  0.05346208  0.06146794]

* 단어 '왕이'의 embedding vector:
[-0.02448205  0.0337246  -0.00199688 -0.0433644  -0.01944972 -0.00437421
  0.03883429  0.01084712]

* 단어 '여왕이'의 embedding vector:
[ 0.02394995  0.03981379  0.01840588  0.00817184 -0.00706507  0.03895424
  0.02431386 -0.00341826]

* 단어 '왕과'의 embedding vector:
[-0.04456154  0.00747989  0.03060367  0.02296619  0.0365935  -0.03161919
  0.02343347  0.05926942]

* 단어 '여왕의'의 embedding vector:
[-0.00644748 -0.00807389  0.01066598 -0.00881461 -0.00090306 -0.02354569
 -0.02736553 -0.00091458]

* 단어 '왕의'의 embedding vector:
[-0.00994621  0.04594902  0.01611301  0.03664145 -0.05396733 -0.0001071
  0.02887074  0.0269608 ]


In [33]:
embedding_matrix_weights = model.layers[0].get_weights()
print(embedding_matrix_weights)
# 동료 수강생분이 질문하셨다고 하셔서 답변 듣고 위와 같이 변수 선언/대입해서 print 해봤는데, 결과를 어떻게 해독해야 할지는 모르겠다..


[array([[-4.88844179e-02, -1.47421397e-02,  5.86934313e-02,
        -1.16672181e-03, -1.66870654e-02,  2.23064777e-02,
        -3.26692201e-02,  7.86636844e-02],
       [-5.63992560e-02,  4.37400304e-02,  1.47184944e-02,
         4.28271331e-02, -1.55261522e-02,  5.90333939e-02,
        -2.89831264e-03, -3.31059955e-02],
       [-7.10835261e-03, -2.08854191e-02,  3.17610428e-02,
        -4.92810383e-02,  2.55024750e-02,  3.14333625e-02,
        -1.95649527e-02, -2.65572648e-02],
       [-5.32011986e-02, -2.71661207e-03, -2.79897801e-03,
         5.32782227e-02,  3.67193855e-02,  5.83015420e-02,
         2.11737566e-02, -3.68028581e-02],
       [-3.41849290e-02,  1.92913245e-02,  2.58296728e-02,
         2.20907014e-02, -1.92163549e-02, -1.06393006e-02,
         5.34620807e-02,  6.14679419e-02],
       [ 5.11816591e-02,  3.43775749e-02,  3.72867398e-02,
        -8.19303747e-03, -1.03689283e-02,  1.04097761e-02,
        -8.53513088e-03, -3.29478309e-02],
       [-4.69360389e-02,  2.10321

# 2026.10.8(목) 21h~

## 영화 긍/부정 리뷰 분류 모델링

In [8]:
from numpy import array
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]
# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
from numpy import array

# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

from tensorflow.keras.preprocessing.text import Tokenizer

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

import pickle # tokenizer 저장/로드를 쉽게 해주는 객체

with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(token, handle, protocol=pickle.HIGHEST_PROTOCOL)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [19]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x) 

from tensorflow.keras.preprocessing.sequence import pad_sequences

# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)  
print("\n패딩 결과:\n", padded_x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

#딥러닝 모델
print("\n딥러닝 모델 시작:")

#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) + 1

#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) # 한 번애 들어가는 문장 길이 = 4개 단어?
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))


딥러닝 모델 시작:


/opt/anaconda3/envs/voice-ai/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 10s 10s/step - accuracy: 0.5000 - loss: 0.6937
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 418ms/step - accuracy: 0.6000 - loss: 0.6914
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 651ms/step - accuracy: 0.6000 - loss: 0.6892
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step - accuracy: 0.6000 - loss: 0.6870
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - accuracy: 0.6000 - loss: 0.6848
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 357ms/step - accuracy: 0.6000 - loss: 0.6825
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - accuracy: 0.7000 - loss: 0.6803
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - accuracy: 0.9000 - loss: 0.6781
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 558ms/step - accuracy: 0.9000 - loss: 0.6759
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - accuracy: 0.9000 - loss: 0.6737
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 659ms/step - accuracy: 0.9000 - loss: 0.6715
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.9000 - loss: 

In [21]:
# 모델 저장
model.save('../models/sentiment_model.keras')

## 학습된 모델을 사용해 새로운 리뷰 예측

In [13]:
# 새로운 문장을 사용한 검증
new_reviews = ["참 재밌네요", "별로였어요", "잘 만든 영화입니다", "지루하네요 재미없어요"]

# 학습 입력 데이터와 동일한 형태로 만들어주기
new_sequences = token.texts_to_sequences(new_reviews)
print(new_sequences)

[[4, 2], [], [5, 6, 10], [17, 20]]


In [14]:
padded_new_sequences = pad_sequences(new_sequences, 4)
print(padded_new_sequences)

[[ 0  0  4  2]
 [ 0  0  0  0]
 [ 0  5  6 10]
 [ 0  0 17 20]]


In [12]:
predictions = model.predict(padded_new_sequences)

# 예측 결과 출력
for review, prediction in zip(new_reviews, predictions):
    print(
        f"리뷰: {review} -> "
        f"예측: {'긍정' if prediction[0] > 0.5 else '부정'} "
        f"(확률: {prediction[0]:.4f})"
    )

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step   
리뷰: 참 재밌네요 -> 예측: 긍정 (확률: 0.5128)
리뷰: 별로였어요 -> 예측: 부정 (확률: 0.4832)
리뷰: 잘 만든 영화입니다 -> 예측: 긍정 (확률: 0.5224)
리뷰: 지루하네요 재미없어요 -> 예측: 부정 (확률: 0.4839)


# 2026.10.8(목) 22h~

## imdb 학습 기본 코드

In [35]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import preprocessing

# 특성으로 사용할 단어의 수
max_features = 10000

# 사용할 텍스트의 길이(가장 빈번한 max_features 개의 단어만 사용합니다)
maxlen = 20

# 정수 리스트로 데이터를 로드합니다.
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

# 리스트를 (samples, maxlen) 크기의 2D 정수 텐서로 변환합니다.
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)
print(x_train[0])
print(y_train[0])

(25000, 20) (25000,)
(25000, 20) (25000,)
[  65   16   38 1334   88   12   16  283    5   16 4472  113  103   32
   15   16 5345   19  178   32]
1


In [36]:
# IMDB 데이터셋의 단어 인덱스 로드
word_index = imdb.get_word_index()

# 인덱스를 단어로 변환하는 딕셔너리 생성
index_to_word = {index + 3: word for word, index in word_index.items()}
index_to_word[0] = "<PAD>" # padding
index_to_word[1] = "<START>" # 문장 시작
index_to_word[2] = "<UNK>" # unknown
index_to_word[3] = "<UNUSED>" # 미사용

# 숫자 시퀀스를 실제 단어 시퀀스로 변환하는 함수
def decode_review(encoded_review):
    return ' '.join([index_to_word.get(i, '?') for i in encoded_review])

# 첫 번째 훈련 데이터 시퀀스를 실제 단어로 변환
decoded_review = decode_review(x_train[0])
print(decoded_review)

story was so lovely because it was true and was someone's life after all that was shared with us all


In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Embedding

print(x_train.shape)

model = Sequential()
# 나중에 임베딩된 입력을 Flatten 층에서 펼치기 위해 Embedding 층에 input_length를 지정합니다.
model.add(Embedding(10000, 8, input_length=maxlen))
# 임베딩 텐서를 (samples, maxlen * 8) 크기의 텐서로 펼칩니다.
model.add(Flatten())
# 분류기를 추가합니다.
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc']) # rmsprop = adam 바로 직전의 optimizer로서 사용해도 무방
model.summary() # 모델 한 번이라도 돌려야 의미있는 값들 볼 수 있음

history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.2)

model.summary()

(25000, 20)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 22s 23ms/step - acc: 0.6287 - loss: 0.6682 - val_acc: 0.6952 - val_loss: 0.6194
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 20s 21ms/step - acc: 0.7445 - loss: 0.5475 - val_acc: 0.7256 - val_loss: 0.5316
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 13s 21ms/step - acc: 0.7826 - loss: 0.4679 - val_acc: 0.7422 - val_loss: 0.5067
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 15s 13ms/step - acc: 0.8071 - loss: 0.4259 - val_acc: 0.7540 - val_loss: 0.4974
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - acc: 0.8252 - loss: 0.3959 - val_acc: 0.7594 - val_loss: 0.4975
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 11s 16ms/step - acc: 0.8386 - loss: 0.3708 - val_acc: 0.7588 - val_loss: 0.4990
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - acc: 0.8501 - loss: 0.3478 - val_acc: 0.7550 - val_loss: 0.5043
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 15s 23ms/step - acc: 0.8626 - loss: 0.3267 - val_acc: 0.7556 - val_loss: 0.5126
Epoch 9/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (32, 20, 8)            │        80,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (32, 160)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (32, 1)                │           161 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 160,324 (626.27 KB)

 Trainable params: 80,161 (313.13 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 80,163 (313.14 KB)

In [38]:
# 임베딩 행렬 추출
embedding_layer = model.layers[0] # 0번째 층이 Embedding 층
embedding_matrix = embedding_layer.get_weights()[0]  # [0] = 단어 embedding

print("임베딩 행렬 모양:", embedding_matrix.shape)  # shape = (10000, 8) = (단어 수, 차원)

# 정수 인덱스 → 단어 매핑 준비
word_index = imdb.get_word_index()  # 단어 → 인덱스
index_to_word = {i + 3: w for w, i in word_index.items()}

index_to_word[0] = "<PAD>"
index_to_word[1] = "<START>"
index_to_word[2] = "<UNK>"
index_to_word[3] = "<UNUSED>"

# 보고 싶은 단어의 임베딩 확인
def show_vector(word):
    idx = word_index.get(word)

    if idx is None or idx + 3 >= embedding_matrix.shape[0]:
        print("단어가 어휘 사전에 없습니다.")
        return

    vec = embedding_matrix[idx + 3]  # +3 오프셋
    print(f"'{word}' 임베딩:", vec)

show_vector("good")
show_vector("bad")
show_vector("movie")
show_vector("bomb")

임베딩 행렬 모양: (10000, 8)
'good' 임베딩: [-0.08129708 -0.00478662 -0.30170977 -0.08260783 -0.06369143 -0.03486211
 -0.18240272 -0.00870821]
'bad' 임베딩: [ 0.41539934  0.48644304  0.50325453  0.11904131  0.15010428 -0.04563529
  0.38244128  0.15015183]
'movie' 임베딩: [ 0.07368486 -0.09514657  0.06905898  0.07249308 -0.04511449 -0.09212798
 -0.1048569   0.03298588]
'bomb' 임베딩: [ 0.44836423  0.42433673  0.36617154 -0.0210053   0.05984773 -0.10143905
  0.32902303 -0.26254508]


In [39]:
import re
from tensorflow.keras.datasets import imdb
from tensorflow.keras import preprocessing

# IMDB 단어 인덱스 로드
word_index = imdb.get_word_index()

# 새로운 리뷰
new_reviews = [
    "It was a boring movie. I do not recommend it.",
    "The movie was extremely disappointing.",
    "I really loved this movie. It was wonderful and excellent.",
    "This was an amazing and enjoyable movie. I highly recommend it."
]

# 새로운 리뷰를 정수 인덱스로 변환
new_sequences = []

for review in new_reviews:
    # 영문과 작은따옴표를 제외한 문장부호 제거
    cleaned_review = re.sub(r"[^a-zA-Z']", " ", review.lower())
    words = cleaned_review.split()

    # IMDB 입력 형식에 맞추어 시작 토큰 추가
    sequence = [1]  # <START>

    for word in words:
        index = word_index.get(word)

        if index is not None and index + 3 < max_features:
            sequence.append(index + 3)
        else:
            sequence.append(2)  # <UNK>

    new_sequences.append(sequence)

# 학습 때와 같은 길이로 패딩
padded_new_sequences = preprocessing.sequence.pad_sequences(
    new_sequences,
    maxlen=maxlen
)

# 변환된 문장 확인
for sequence in padded_new_sequences:
    print(decode_review(sequence))

<PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <START> it was a boring movie i do not recommend it
<PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <START> the movie was extremely disappointing
<PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <START> i really loved this movie it was wonderful and excellent
<PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <START> this was an amazing and enjoyable movie i highly recommend it


In [40]:
# 예측
predictions = model.predict(padded_new_sequences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 572ms/step


In [41]:
# 결과 출력
for review, prediction in zip(new_reviews, predictions):
    probability = prediction[0]
    result = "긍정" if probability > 0.5 else "부정"

    print(f"리뷰: {review}")
    print(f"예측: {result} (긍정 확률: {probability:.4f})")
    print()

리뷰: It was a boring movie. I do not recommend it.
예측: 부정 (긍정 확률: 0.0071)

리뷰: The movie was extremely disappointing.
예측: 부정 (긍정 확률: 0.0002)

리뷰: I really loved this movie. It was wonderful and excellent.
예측: 긍정 (긍정 확률: 0.9681)

리뷰: This was an amazing and enjoyable movie. I highly recommend it.
예측: 긍정 (긍정 확률: 0.9115)

