In [2]:
import sys
import tensorflow as tf

print(sys.executable)
print(tf.__version__)

2026-09-17 19:25:07.489907: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


/opt/anaconda3/envs/voice-ai/bin/python
2.16.2


In [3]:
import numpy as np

In [4]:
my_list = [0,1,2,3,4,5,6,7,8,9]

In [5]:
print(type(my_list))

<class 'list'>


In [6]:
ar = np.array(my_list)

In [7]:
print(type(ar))

<class 'numpy.ndarray'>


In [8]:
a1 = [1,2,3]
b1 = [4,5,6]
print(a1+b1)

[1, 2, 3, 4, 5, 6]


In [9]:
a1 = [1,2,3]
b1 = [4,5,6]
aa = np.array(a1)
ba = np.array(b1)
print(aa+ba)

[5 7 9]


# 2026.9.17(목) 19h~

In [4]:
d = np.array([
                [
                    [1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]
                ],
                [
                    [11, 12, 13, 14],
                    [15, 16, 17, 18],
                    [19, 20, 21, 22]
                ]
            ]) # 2 x 3 x 4 array

In [5]:
a = np.array([ [0,1,2,3],
               [4,5,6,7]
             ])

a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

다음 행렬과 같은 행렬이 있다.

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [7]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [36]:
# 1. 이 행렬에서 값 7을 인덱싱한다
print(m[1,2]) # 내가 쓴 거 -> ok
print(m[1][2]) # 강사님

# 2. 이 행렬에서 값 14을 인덱싱한다
print(m[2,4]) # 내가 쓴 거 -> ok
print(m[-1,-1]) # 강사님

# 3. 이 행렬에서 배열 [6, 7]을 슬라이싱한다
print(m[1:2,1:3]) # 내가 쓴 거 -> 틀림
print(m[1,1:3]) # 강사님

# 4. 이 행렬에서 배열 [7, 12]을 슬라이싱한다
print(m[1:3,2:3]) # 내가 쓴 거 -> 틀림
print(m[1:,2]) # 강사님

# 5. 이 행렬에서 배열 [[3, 4], [8, 9]]을 슬라이싱한다
print(m[0:2,3:5]) # 내가 쓴 거 = 강사님 -> ok

7
7
14
14
[[6 7]]
[6 7]
[[ 7]
 [12]]
[ 7 12]
[[3 4]
 [8 9]]


### boolean indexing
filtering에 사용됨

In [38]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False,])
a[idx]

array([0, 2, 4, 6, 8])

### 정수 indexing

In [39]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a[:,]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
my_a = np.array([1, 2, 3])
print(my_a)

idx = [0,2,1]
print(my_a[0])
print(my_a[idx])

[1 2 3]
1
[1 3 2]


In [42]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
# 1. 이 배열에서 3의 배수를 찾아라.
print(x[x % 3 == 0])

# 2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(x[x % 4 == 1])

# 3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
