In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])
print(x.dtype)

int64


In [5]:
x = np.array([1.1,2.4,3.7])
print(x.dtype)

float64


In [4]:
x = np.array([1.1,2,3])
print(x.dtype)

float64


### inf, nan
- infinity
- not a number

In [7]:
a = np.array([1.0, 2.0, -3.0, 0.0])
b = np.array([0.0, 1.0, 0.0, 0.0])
c = a / b

print(c)

[ inf   2. -inf  nan]


/var/folders/y2/5m8dl9kj7yl_xvfwnl0xlj8m0000gn/T/ipykernel_36146/3065340157.py:3: RuntimeWarning: divide by zero encountered in divide
  c = a / b
/var/folders/y2/5m8dl9kj7yl_xvfwnl0xlj8m0000gn/T/ipykernel_36146/3065340157.py:3: RuntimeWarning: invalid value encountered in divide
  c = a / b


In [9]:
a = np.zeros(5)
print(a.dtype)
a

float64


array([0., 0., 0., 0., 0.])

In [12]:
b1 = np.zeros([2,3])
print(b1)

b2 = np.zeros((2,3)) # 강사님 코드
print(b2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
c = np.zeros((5,2), dtype="u4") # 또는 i
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=uint32)

In [16]:
b3 = np.ones_like(b, dtype="i")
b3

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [18]:
d1 = np.ones((3,4))
d1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
d2 = np.zeros_like(d1, dtype="u4")
d2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

In [21]:
g = np.empty((4,3)) # 메모리에 있는 쓰레기 값
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

line space를 log space보다 더 많이 씀

In [27]:
print(np.linspace(0, 100, 11))
print(np.linspace(0, 100, 12))
print(np.linspace(0, 100, 5))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[  0.           9.09090909  18.18181818  27.27272727  36.36363636
  45.45454545  54.54545455  63.63636364  72.72727273  81.81818182
  90.90909091 100.        ]
[  0.  25.  50.  75. 100.]


In [29]:
print(np.logspace(0.1, 1, 10))

[ 1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171
  5.01187234  6.30957344  7.94328235 10.        ]


### 전치 연산

### reshape
ai 모델링할 때, 특히 예측할 때, 많이 씀

In [32]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
print(a.reshape(3,4))
print(a.reshape(3,-1))
print(a.reshape(4,-1))
print(a.reshape(5,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: cannot reshape array of size 12 into shape (5,newaxis)